-- MySQL Script generated by MySQL Workbench
-- शनिबार  21 नवम्बर 2015 11:58:39 पूर्वाह्न NPT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema NOC
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema NOC
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `NOC` DEFAULT CHARACTER SET utf8 ;
USE `NOC` ;

-- -----------------------------------------------------
-- Table `NOC`.`PetrolPumps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOC`.`PetrolPumps` ;

CREATE TABLE IF NOT EXISTS `NOC`.`PetrolPumps` (
  `PetrolPumpsID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(1000) NOT NULL,
  `Capacity` INT(11) NOT NULL,
  `Location` VARCHAR(1000) NOT NULL,
  `GeoLocation` POINT NULL DEFAULT NULL,
  `Owner` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`PetrolPumpsID`),
  UNIQUE INDEX `PetrolPumpsID_UNIQUE` (`PetrolPumpsID` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'This table contains petrolpumps and its related data.';


-- -----------------------------------------------------
-- Table `NOC`.`Distribution`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOC`.`Distribution` ;

CREATE TABLE IF NOT EXISTS `NOC`.`Distribution` (
  `DistributionID` INT NOT NULL AUTO_INCREMENT,
  `SentAmount` INT NOT NULL,
  `fk_PetrolPumpsID` INT NOT NULL,
  `AvailableDate` DATE NOT NULL,
  PRIMARY KEY (`DistributionID`),
  INDEX `fk_petrol_pumps_idx` (`fk_PetrolPumpsID` ASC),
  UNIQUE INDEX `DistributionID_UNIQUE` (`DistributionID` ASC),
  CONSTRAINT `fk_petrol_pumps`
    FOREIGN KEY (`fk_PetrolPumpsID`)
    REFERENCES `NOC`.`PetrolPumps` (`PetrolPumpsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `NOC`.`UserTokens`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `NOC`.`UserTokens` ;

CREATE TABLE IF NOT EXISTS `NOC`.`UserTokens` (
  `UserTokensID` INT NOT NULL AUTO_INCREMENT,
  `BillBookID` VARCHAR(45) NOT NULL,
  `Token` VARCHAR(45) NOT NULL,
  `fk_PetrolPumpsID` INT NOT NULL,
  `UserName` VARCHAR(1000) NOT NULL,
  `PhoneNumber` INT NOT NULL,
  `FuelType` VARCHAR(45) NOT NULL,
  `VehicleType` VARCHAR(45) NOT NULL,
  `VehicleID` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserTokensID`),
  INDEX `fk_PetrolPumpsID_idx` (`fk_PetrolPumpsID` ASC),
  UNIQUE INDEX `UserTokensID_UNIQUE` (`UserTokensID` ASC),
  CONSTRAINT `fk_PetrolPumpsID`
    FOREIGN KEY (`fk_PetrolPumpsID`)
    REFERENCES `NOC`.`PetrolPumps` (`PetrolPumpsID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `NOC`.`PetrolPumps`
-- -----------------------------------------------------
START TRANSACTION;
USE `NOC`;
INSERT INTO `NOC`.`PetrolPumps` (`PetrolPumpsID`, `Name`, `Capacity`, `Location`, `GeoLocation`, `Owner`) VALUES (2, 'Namaste Fuel Center', 20000, 'Satdobato', NULL, 'Ram Gopal');
INSERT INTO `NOC`.`PetrolPumps` (`PetrolPumpsID`, `Name`, `Capacity`, `Location`, `GeoLocation`, `Owner`) VALUES (3, 'Koteshwor Fuel Center', 30000, 'Halchowk', NULL, 'Shyam Basyal');
INSERT INTO `NOC`.`PetrolPumps` (`PetrolPumpsID`, `Name`, `Capacity`, `Location`, `GeoLocation`, `Owner`) VALUES (4, 'Nata petrol pump', 10000, 'Gongabu', NULL, 'Sita Nepal');
INSERT INTO `NOC`.`PetrolPumps` (`PetrolPumpsID`, `Name`, `Capacity`, `Location`, `GeoLocation`, `Owner`) VALUES (1, 'Hello Petrol Pump', 10000, '', NULL, 'Hari Jai');

COMMIT;


-- -----------------------------------------------------
-- Data for table `NOC`.`UserTokens`
-- -----------------------------------------------------
START TRANSACTION;
USE `NOC`;
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (1, '23424324', '323452', 1, 'Shaym Bhakt Tripathi', 984957465, 'Petrol', 'car', 'ba 2 kha 3423');
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (2, '3423423423', '233333', 1, 'Ram Gopal ', 985235689, 'Diesel', 'car', 'ba 4 kha 3422');
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (3, '342532', '46456', 2, 'Laxmi Sni', 984568458, 'Petrol', 'Scoter', 'ba 32 kha 3453');
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (4, '23453245', '453563', 3, 'Hira lal', 984568452, 'Petrol', 'Bike', 'ga 34 kha 342');
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (5, '546345', '45643', 1, 'Nitesh Kumar', 342423523, 'Petrol', 'Bike', 'ma 2 kha 3432');
INSERT INTO `NOC`.`UserTokens` (`UserTokensID`, `BillBookID`, `Token`, `fk_PetrolPumpsID`, `UserName`, `PhoneNumber`, `FuelType`, `VehicleType`, `VehicleID`) VALUES (6, '34522435', '45564', 2, 'Hera Kumar', 984323432, 'Diesel', 'car', 'ba 4 kha 43543');

COMMIT;

